# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2b516c10167bcf033032d9a726c3a647e02a33e7a86fc076a58cc6dc8434365c8522d47970ba36fb42da4076357d4eed7edcbc6e23476204b4fedc32452d9ca7

test:
  secret_key_base: f509e7193485e70fb4bef73755ca56ef9eeb64737cb6f207acdac53bab8cb0146bb4a833370288402ab39f7bcf45cf7b99ba86a56d74d4962dc616c26c686e4d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: 2a7ac0fd16e3ed38429e73e2cbddbf85f520dc85740ae3550772497db34d91a18f845e5d296003ee3fcce0a98aeee3fc9accb29f7be3f02592779151fbf656ee
  secret_token: 2a7ac0fd16e3ed38429e73e2cbddbf85f520dc85740ae3550772497db34d91a18f845e5d296003ee3fcce0a98aeee3fc9accb29f7be3f02592779151fbf656ee

# vo por aqui mesmo pq nao tá pegando o env no servidor nao sei pq
